// packages/react/src/dev/lib/channel.ts
import { useState } from 'react';

interface Channel<T> {
    (): T;
    (setter: T | ((prev: T) => T)): void;
}

function useChannel<T>(init: T): Channel<T> {
    const [get, set] = useState(init);

    function controller(setter?: ((prev: T) => T) | T): T | void {
        if (arguments.length === 0) {
            return get;
        } else {
            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
            // @ts-ignore
            set((prev) => (typeof setter === 'function' ? setter(prev) : setter));
        }
    }

    return controller as unknown as Channel<T>;
}

export { useChannel };
export type { Channel };

// packages/solid/src/dev/lib/channel.ts
import { createSignal } from 'solid-js';
import type { Setter } from 'solid-js'

interface Channel<T> {
    (): T;
    (setter: Setter<T>): T;
}

function channel<T>(init: T): Channel<T> {
    const [get, set] = createSignal(init);

    function controller(setter?: Setter<T>) {
        if (arguments.length === 0) {
            return get();
        } else {
            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            return set(setter!);
        }
    }

    return controller as Channel<T>;
}

export { channel };
export type { Channel };
