// packages/solid/src/components/Slidy/Slidy.tsx
import { Show, For, merge, createSignal, untrack, flush } from 'solid-js';

import { Arrow, Core, Image, Progress, Thumbnail, Navigation } from '..';
import { SlidyContext, useSlidy } from '../Context/Context';

import { execute, isFunction, format } from '@slidy/assets/scripts/utils';
import { iconChevron } from '@slidy/assets/icons';

import { i18nDefaults } from './i18n';
import { classNames as classNamesDefaults } from './slidy.styles';

import '@slidy/assets/styles/slidy.module.css';

import type { Props } from './Slidy.types';
import type { Component } from 'solid-js';

const defaultProps: Props = {
    arrows: true,
    vertical: false,
    background: false,
    counter: true,
    getImgSrc: (item) => (item as unknown as { src: string }).src ?? '',
    getThumbSrc: (item) => (item as unknown as { src: string }).src ?? '',
    navigation: false,
    loop: false,
    groups: 0,
    progress: false,
    slides: [],
    thumbnail: false,
    index: () => 0,
    classNames: classNamesDefaults,
    i18n: i18nDefaults,
};

const Slidy: Component<Partial<Props>> = (rawProps) => {
    const props = merge(defaultProps as unknown as Required<Props>, rawProps);

    const [index, setIndex] = isFunction(props.setIndex)
        ? [props.index, props.setIndex]
        : createSignal(untrack(props.index));

    const length = () => props.slides.length;

    const handleClick = (event: Event): void => {
        const element = event.target as HTMLElement;

        if (element.nodeName !== 'BUTTON') return;

        if (element.dataset.index) {
            setIndex(parseInt(element.dataset.index));
            return;
        }

        if (element.dataset.step) {
            setIndex(parseInt(element.dataset.step) + untrack(index));
            return;
        }
    };

    const onIndex: Props['onIndex'] = (e) => {
        flush();
        setIndex(e.detail.index);
    };

    return (
        <SlidyContext value={{ classNames: props.classNames, i18n: props.i18n }}>
            <section
                aria-roledescription={props.i18n.carousel}
                aria-orientation={props.vertical ? 'vertical' : 'horizontal'}
                class={{
                    [props.classNames && props.classNames.root]: true,

                    groups: props.groups > 1,
                }}
                style={{
                    '--slidy-group-items': props.groups,
                }}
                id={props.id}
                onClick={handleClick}
            >
                <Show when={props.counter || props.overlay}>
                    <div class={props.classNames?.overlay}>
                        <Show when={props.counter}>
                            <output class={props.classNames?.counter}>
                                {index() + 1} / {length()}
                            </output>
                        </Show>
                        {isFunction(props.overlay) && props.overlay()}
                    </div>
                </Show>
                <Core
                    animation={props.animation}
                    axis={props.axis}
                    clamp={props.clamp}
                    className={props.classNames?.slides}
                    duration={props.duration}
                    easing={props.easing}
                    gravity={props.gravity}
                    indent={props.indent}
                    index={index()}
                    loop={props.loop}
                    sensity={props.sensity}
                    snap={props.snap}
                    plugins={/* @once */ props.plugins}
                    onResize={props.onResize}
                    onMount={props.onMount}
                    onMove={props.onMove}
                    onIndex={execute(onIndex, props.onIndex)}
                    onKeys={props.onKeys}
                    onUpdate={props.onUpdate}
                    onDestroy={props.onDestroy}
                    onMutate={props.onMutate}
                >
                    <For each={props.slides}>
                        {(item, i) => {
                            const active = () => index() === i();

                            if (props.children) {
                                return props.children(item());
                            }

                            return (
                                <li
                                    aria-current={active() ? 'true' : undefined}
                                    aria-label={format(props.i18n.counter, i() + 1, length())}
                                    aria-roledescription={props.i18n.slide}
                                    class={{
                                        [props.classNames && props.classNames.slide]: true,

                                        active: active(),
                                        bg: props.background,
                                    }}
                                    role="group"
                                    style={{
                                        '--_slidy-slide-bg': props.background
                                            ? `url("${props.getImgSrc(item())}")`
                                            : undefined,
                                    }}
                                >
                                    <Show when={!props.background}>
                                        <Image {...item()} src={props.getImgSrc(item())} />
                                    </Show>
                                </li>
                            );
                        }}
                    </For>
                </Core>
                <Show
                    when={props.arrows === true}
                    fallback={isFunction(props.arrows) && props.arrows()}
                >
                    <For each={[-1, 1]}>
                        {(direction) => (
                            <Arrow
                                direction={direction()}
                                index={index()}
                                items={length()}
                                loop={props.loop}
                                step={props.clamp > 0 ? props.clamp : 1}
                                vertical={props.vertical}
                            >
                                <Show
                                    when={!props.arrow}
                                    fallback={isFunction(props.arrow) && props.arrow()}
                                >
                                    <svg class="slidy-arrow-icon" viewBox={iconChevron.viewBox}>
                                        <path d={iconChevron.path} />
                                    </svg>
                                </Show>
                            </Arrow>
                        )}
                    </For>
                </Show>

                <Show when={props.progress}>
                    <Progress
                        value={index() + 1}
                        max={length()}
                        vertical={props.vertical}
                        onInput={(e) => {
                            setIndex(e.currentTarget.valueAsNumber - 1);
                        }}
                    />
                </Show>

                <Show
                    when={props.thumbnail === true}
                    fallback={isFunction(props.thumbnail) && props.thumbnail()}
                >
                    <Thumbnail
                        active={index()}
                        background={props.background}
                        duration={props.duration}
                        easing={props.easing}
                        getImgSrc={props.getThumbSrc}
                        indent={props.indent}
                        index={index()}
                        loop={props.loop}
                        sensity={props.sensity}
                        slides={props.slides}
                        onSelect={setIndex}
                    />
                </Show>
                <Show when={props.navigation}>
                    <Navigation
                        current={index() + 1}
                        start={1}
                        end={length()}
                        vertical={props.vertical}
                    />
                </Show>
            </section>
        </SlidyContext>
    );
};

export { useSlidy };
export default Slidy;

// packages/svelte/src/components/Slidy/Slidy.svelte
<script lang="ts" module>
	import { setContext, type Snippet } from "svelte";
	import { Arrow, Core, Image, Navigation, Progress, Thumbnail } from "../index";
	import { format } from "@slidy/assets/scripts/utils";
	import { classNames as classNamesDefault } from "./slidy.styles";
	import { iconChevron } from "@slidy/assets/icons";
	import { i18nDefaults } from "./i18n";

	import "@slidy/assets/styles/slidy.module.css";

	import type { SlidyOptions } from "./Slidy.types";
</script>

<script lang="ts">
	let {
		animation= undefined,
		arrows = true,
		axis = "x",
		background = false,
		counter = true,
		clamp = 0,
		classNames = classNamesDefault,
		duration = 450,
		easing = (t) => t,
		getImgSrc= (item) => item.src || "",
		getThumbSrc = (item) => getImgSrc(item),
		navigation = false,
		gravity = 1.2,
		i18n = i18nDefaults,
		indent = 2,
		index = $bindable(0),
		loop = false,
		groups = 0,
		plugins = [],
		progress = false,
		sensity = 5,
		slides = [],
		snap = undefined,
		thumbnail = false,
		vertical = false,
		onmove,onmount, onkeys, onresize, onupdate, ondestroy,
		children, overlay, thumbnails, arrrows, arrrow
	}: Partial<SlidyOptions & {
		children: Snippet, overlay: Snippet, thumbnails: Snippet, arrrows: Snippet, arrrow: Snippet
	}> = $props()

	setContext("classNames", classNames);
	setContext("i18n", i18n);

	const length = $derived(slides.length);

	const handleClick = (event: Event): void => {
		const element = event.target as HTMLElement;

		if (element.nodeName !== "BUTTON") return;

		if (element.dataset.index) {
			index = parseInt(element.dataset.index);
			return;
		}

		if (element.dataset.step) {
			index = parseInt(element.dataset.step) + index;
			return;
		}
	};
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_role_supports_aria_props_implicit -->
<section
	aria-roledescription={i18n.carousel}
	aria-orientation={vertical ? "vertical" : "horizontal"}
	class={classNames?.root}
	class:groups={groups > 1}
	style:--slidy-group-items={groups}
	onclick={handleClick}
>
	{#if counter}
		<div class={classNames?.overlay}>
			{#if counter}
				<output class={classNames?.counter}>
					{format(i18n.counter, index + 1, length)}
				</output>
			{/if}
			{@render overlay?.()}
		</div>
	{/if}

	<Core
		{animation}
		{axis}
		{clamp}
		{duration}
		{easing}
		{gravity}
		{indent}
		{index}
		{loop}
		{plugins}
		{sensity}
		{snap}
		{onmove}
		{onkeys}
		{onmount}
		{onresize}
		{onupdate}
		{ondestroy}
		className={classNames?.slides}
		onindex={e => index = e.detail.index}
	>
		{#each slides as item, i (item.id ?? getImgSrc(item) ?? i)}
			{@const active = i === index}
			<li
				aria-current={active ? "true" : undefined}
				aria-label={format(i18n.counter, i, length)}
				aria-roledescription={i18n.slide}
				class={classNames?.slide}
				class:active
				class:bg={background}
				role="group"
				style:--_slidy-slide-bg={background ? `url(${getImgSrc(item)}` : undefined}
			>
				{#if children}
					{@render children()}
				{:else}
					{#if !background}
						<Image src={getImgSrc(item)} {...item} />
					{/if}
				{/if}
			</li>
		{/each}
	</Core>

	{#if arrows}
		{#if arrrows}
			{@render arrrows?.()}
		{:else}
			{#each [ -1, 1 ] as direction}
				<Arrow
					{direction}
					{index}
					items={length}
					{loop}
					step={clamp > 0 ? clamp : 1}
					{vertical}
				>
					{#if arrrow}
						{@render arrrow?.()}
					{:else}
						<svg
							class="slidy-arrow-icon"
							viewBox={iconChevron.viewBox}
							xmlns="http://www.w3.org/2000/svg"
						>
							<path d={iconChevron.path}></path>
						</svg>
					{/if}
				</Arrow>
			{/each}
		{/if}
	{/if}

	{#if progress}
		<Progress
			value={index + 1}
			max={length}
			{vertical}
			change={valueAsNumber => index = valueAsNumber - 1}
		/>
	{/if}

	{#if thumbnail}
		{#if thumbnails}
			{@render thumbnails()}
		{:else}
			<Thumbnail
				{background}
				{duration}
				{easing}
				{indent}
				{loop}
				{sensity}
				{slides}
				active={index}
				index={index}
				getImgSrc={getThumbSrc}
				select={indx => index = indx}
			/>
		{/if}
	{/if}

	{#if navigation}
		<Navigation current={index + 1} start={1} end={length} {vertical} />
	{/if}
</section>
