// packages/solid/src/components/Slidy/Slidy.tsx
import { Show, For, merge, createSignal, untrack, flush } from 'solid-js';

import { Arrow, Core, Image, Progress, Thumbnail, Navigation } from '..';
import { SlidyContext, useSlidy } from '../Context/Context';

import { execute, isFunction, format } from '@slidy/assets/scripts/utils';
import { iconChevron } from '@slidy/assets/icons';

import { i18nDefaults } from './i18n';
import { classNames as classNamesDefaults } from './slidy.styles';

import '@slidy/assets/styles/slidy.module.css';

import type { Props } from './Slidy.types';
import type { Component } from 'solid-js';

const defaultProps: Props = {
    arrows: true,
    vertical: false,
    background: false,
    counter: true,
    getImgSrc: (item) => (item as unknown as { src: string }).src ?? '',
    getThumbSrc: (item) => (item as unknown as { src: string }).src ?? '',
    navigation: false,
    loop: false,
    groups: 0,
    progress: false,
    slides: [],
    thumbnail: false,
    index: () => 0,
    classNames: classNamesDefaults,
    i18n: i18nDefaults,
};

const Slidy: Component<Partial<Props>> = (rawProps) => {
    const props = merge(defaultProps as unknown as Required<Props>, rawProps);

    const [index, setIndex] = isFunction(props.setIndex)
        ? [props.index, props.setIndex]
        : createSignal(untrack(props.index));

    const length = () => props.slides.length;

    const handleClick = (event: Event): void => {
        const element = event.target as HTMLElement;

        if (element.nodeName !== 'BUTTON') return;

        if (element.dataset.index) {
            setIndex(parseInt(element.dataset.index));
            return;
        }

        if (element.dataset.step) {
            setIndex(parseInt(element.dataset.step) + untrack(index));
            return;
        }
    };

    const onIndex: Props['onIndex'] = (e) => {
        flush();
        setIndex(e.detail.index);
    };

    return (
        <SlidyContext value={{ classNames: props.classNames, i18n: props.i18n }}>
            <section
                aria-roledescription={props.i18n.carousel}
                aria-orientation={props.vertical ? 'vertical' : 'horizontal'}
                class={{
                    [props.classNames && props.classNames.root]: true,

                    groups: props.groups > 1,
                }}
                style={{
                    '--slidy-group-items': props.groups,
                }}
                id={props.id}
                onClick={handleClick}
            >
                <Show when={props.counter || props.overlay}>
                    <div class={props.classNames?.overlay}>
                        <Show when={props.counter}>
                            <output class={props.classNames?.counter}>
                                {index() + 1} / {length()}
                            </output>
                        </Show>
                        {isFunction(props.overlay) && props.overlay()}
                    </div>
                </Show>
                <Core
                    animation={props.animation}
                    axis={props.axis}
                    clamp={props.clamp}
                    className={props.classNames?.slides}
                    duration={props.duration}
                    easing={props.easing}
                    gravity={props.gravity}
                    indent={props.indent}
                    index={index()}
                    loop={props.loop}
                    sensity={props.sensity}
                    snap={props.snap}
                    plugins={/* @once */ props.plugins}
                    onResize={props.onResize}
                    onMount={props.onMount}
                    onMove={props.onMove}
                    onIndex={execute(onIndex, props.onIndex)}
                    onKeys={props.onKeys}
                    onUpdate={props.onUpdate}
                    onDestroy={props.onDestroy}
                    onMutate={props.onMutate}
                >
                    <For each={props.slides}>
                        {(item, i) => {
                            const active = () => index() === i();

                            if (props.children) {
                                return props.children(item());
                            }

                            return (
                                <li
                                    aria-current={active() ? 'true' : undefined}
                                    aria-label={format(props.i18n.counter, i() + 1, length())}
                                    aria-roledescription={props.i18n.slide}
                                    class={{
                                        [props.classNames && props.classNames.slide]: true,

                                        active: active(),
                                        bg: props.background,
                                    }}
                                    role="group"
                                    style={{
                                        '--_slidy-slide-bg': props.background
                                            ? `url("${props.getImgSrc(item())}")`
                                            : undefined,
                                    }}
                                >
                                    <Show when={!props.background}>
                                        <Image {...item()} src={props.getImgSrc(item())} />
                                    </Show>
                                </li>
                            );
                        }}
                    </For>
                </Core>
                <Show
                    when={props.arrows === true}
                    fallback={isFunction(props.arrows) && props.arrows()}
                >
                    <For each={[-1, 1]}>
                        {(direction) => (
                            <Arrow
                                direction={direction()}
                                index={index()}
                                items={length()}
                                loop={props.loop}
                                step={props.clamp > 0 ? props.clamp : 1}
                                vertical={props.vertical}
                            >
                                <Show
                                    when={!props.arrow}
                                    fallback={isFunction(props.arrow) && props.arrow()}
                                >
                                    <svg class="slidy-arrow-icon" viewBox={iconChevron.viewBox}>
                                        <path d={iconChevron.path} />
                                    </svg>
                                </Show>
                            </Arrow>
                        )}
                    </For>
                </Show>

                <Show when={props.progress}>
                    <Progress
                        value={index() + 1}
                        max={length()}
                        vertical={props.vertical}
                        onInput={(e) => {
                            setIndex(e.currentTarget.valueAsNumber - 1);
                        }}
                    />
                </Show>

                <Show
                    when={props.thumbnail === true}
                    fallback={isFunction(props.thumbnail) && props.thumbnail()}
                >
                    <Thumbnail
                        active={index()}
                        background={props.background}
                        duration={props.duration}
                        easing={props.easing}
                        getImgSrc={props.getThumbSrc}
                        indent={props.indent}
                        index={index()}
                        loop={props.loop}
                        sensity={props.sensity}
                        slides={props.slides}
                        onSelect={setIndex}
                    />
                </Show>
                <Show when={props.navigation}>
                    <Navigation
                        current={index() + 1}
                        start={1}
                        end={length()}
                        vertical={props.vertical}
                    />
                </Show>
            </section>
        </SlidyContext>
    );
};

export { useSlidy };
export default Slidy;

// packages/svelte/src/component/Slidy.svelte
<script lang="ts" context="module">
	import { slidy } from "@slidy/core";
	import { Arrow, Image, Pagination } from "./components";
	import { clamp as clampValue } from "../helpers/utils";
	import "./slidy.module.css";

	import type { SlidyOptions, ChangeSlide, Slide, GetSrc } from "../types";
</script>

<script lang="ts">
	type $$Props = SlidyOptions;

	export let arrows = true;
	export let background = false;
	export let clamp = false;
	export let className: $$Props["className"] = "";
	export let getImgSrc: GetSrc = (item: Slide) => item.src ?? "";
	export let navigation = true;
	export let duration = 450;
	export let gravity = 1.2;
	export let id: $$Props["id"] = undefined;
	export let index = 0;
	export let loop = false;
	export let position = 0;
	export let slides: $$Props["slides"] = [];
	export let snap = true;
	export let vertical = false;

	$: length = slides.length;

	/**
	 * Route to the desired slide index.
	 */
	const goto: ChangeSlide = (slide) => {
		if (typeof slide === "number" && !Number.isNaN(slide)) {
			index = clampValue(slide, 0, length - 1);
		}
	};

	const handleClick = (event: Event): void => {
		const element = event.target as HTMLElement;

		if (element.nodeName !== "BUTTON") return;

		if (element.dataset.index) {
			goto(parseInt(element.dataset.index));
			return;
		}

		if (element.dataset.step) {
			goto(parseInt(element.dataset.step) + index);
			return;
		}
	};
</script>

<section aria-roledescription="carousel" class="slidy {className}" class:vertical {id} tabindex="0" on:click={handleClick}>
	<slot name="counter" {index} amount={length}>
		<output class="slidy-counter">
			{index + 1} / {length}
		</output>
	</slot>
	<ul
		class="slidy-slides"
		aria-live="polite"
		use:slidy={{
			length: length,
			vertical,
			duration,
			gravity,
			index,
			clamp,
			snap,
			loop,
		}}
		on:mount={(e) => console.log(e)}
		on:move={(e) => {
			index = e.detail.index;
			position = e.detail.position;
		}}
	>
		{#each slides as item, i (item.id ?? getImgSrc(item) ?? i)}
			<li
				aria-current={i === index ? "true" : undefined}
				aria-label={`${i} of ${length}`}
				aria-roledescription="slide"
				class="slidy-slide"
				class:active={i === index}
				class:background
				style={background ? `--slidy-slide-bg: url(${getImgSrc(item)});` : undefined}
				role="group"
			>
				<slot {item}>
					{#if !background}
						<Image src={getImgSrc(item)} {...item} />
					{/if}
				</slot>
			</li>
		{/each}
	</ul>

	{#if arrows}
		<slot name="arrows">
			{#each [ -1, 1 ] as type}
				<Arrow {type} {index} items={length} {loop} {vertical} />
			{/each}
		</slot>
	{/if}

	{#if navigation}
		<Pagination current={index + 1} start={1} end={length} {vertical} />
	{/if}
</section>
