// packages/svelte/src/components/ButtonAutoplay/ButtonAutoplay.svelte
<script lang="ts">
	import "@slidy/assets/styles/button-autoplay.module.css";

	export let disabled = false;
	export let state: "play" | "pause" | "stop";

	let r = 15;
	let stroke = 2;

	const iconPath = {
		"play": "M7.61,4.61a.75.75,0,0,0-1.11.66V18.73a.75.75,0,0,0,1.11.65L20,12.66a.75.75,0,0,0,0-1.32ZM5,5.27a2.25,2.25,0,0,1,3.33-2L20.69,10a2.26,2.26,0,0,1,0,4L8.33,20.7a2.25,2.25,0,0,1-3.33-2Z",
		"pause": "M5.75,3A1.75,1.75,0,0,0,4,4.75v14.5A1.75,1.75,0,0,0,5.75,21h3.5A1.75,1.75,0,0,0,11,19.25V4.75A1.75,1.75,0,0,0,9.25,3ZM5.5,4.75a.25.25,0,0,1,.25-.25h3.5a.25.25,0,0,1,.25.25v14.5a.25.25,0,0,1-.25.25H5.75a.25.25,0,0,1-.25-.25ZM14.75,3A1.75,1.75,0,0,0,13,4.75v14.5A1.75,1.75,0,0,0,14.75,21h3.5A1.75,1.75,0,0,0,20,19.25V4.75A1.75,1.75,0,0,0,18.25,3ZM14.5,4.75a.25.25,0,0,1,.25-.25h3.5a.25.25,0,0,1,.25.25v14.5a.25.25,0,0,1-.25.25h-3.5a.25.25,0,0,1-.25-.25Z",
		"stop": "M5.75,3h12.5A2.75,2.75,0,0,1,21,5.75v12.5A2.75,2.75,0,0,1,18.25,21H5.75A2.75,2.75,0,0,1,3,18.25V5.75A2.75,2.75,0,0,1,5.75,3Zm0,1.5A1.25,1.25,0,0,0,4.5,5.75v12.5A1.25,1.25,0,0,0,5.75,19.5h12.5a1.25,1.25,0,0,0,1.25-1.25V5.75A1.25,1.25,0,0,0,18.25,4.5Z"
	};
</script>

<div class="slidy-autoplay" style:--slidy-autoplay-stroke-length={2 * Math.PI * r}>
	<!-- Indicator -->
	<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {2 * r + stroke} {2 * r + stroke}">
		<path
			stroke="var(--slidy-counter-bg, #4e4e4ebf)"
			stroke-width="{stroke}px"
			fill="none"
			d="M {r + stroke / 2}, {r + stroke / 2} m -{r}, 0 a {r},{r} 0 1,0 {2 * r},0 a {r},{r} 0 1,0 {-2 * r},0"
		/>
		<path
			class="slidy-autoplay-indicator {state}"
			stroke="var(--slidy-autoplay-indicator-accent, lightpink)"
			stroke-width="{stroke}px"
			fill="none"
			d="M {r + stroke / 2}, {r + stroke / 2} m -{r}, 0 a {r},{r} 0 1,0 {2 * r},0 a {r},{r} 0 1,0 {-2 * r},0"
		/>
	</svg>
	<button
		{disabled}
		on:click
	>
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
			<path d="{iconPath[state]}" />
		</svg>
	</button>
</div>

// packages/solid/src/components/ButtonAutoplay/ButtonAutoplay.tsx
import { mergeProps } from 'solid-js';
import { useSlidy } from '../Slidy/Slidy';

import '@slidy/assets/styles/button-autoplay.module.css';

import type { Component } from 'solid-js';

type State = 'play' | 'pause' | 'stop';

interface Options {
    disabled: boolean;
    state: State;

    onClick: () => void;
}

const defaultProps: Options = {
    disabled: false,
    state: 'stop',
    onClick: () => {
        //
    },
};

const r = 15;
const stroke = 2;

const iconPath = {
    play: 'M7.61,4.61a.75.75,0,0,0-1.11.66V18.73a.75.75,0,0,0,1.11.65L20,12.66a.75.75,0,0,0,0-1.32ZM5,5.27a2.25,2.25,0,0,1,3.33-2L20.69,10a2.26,2.26,0,0,1,0,4L8.33,20.7a2.25,2.25,0,0,1-3.33-2Z',
    pause: 'M5.75,3A1.75,1.75,0,0,0,4,4.75v14.5A1.75,1.75,0,0,0,5.75,21h3.5A1.75,1.75,0,0,0,11,19.25V4.75A1.75,1.75,0,0,0,9.25,3ZM5.5,4.75a.25.25,0,0,1,.25-.25h3.5a.25.25,0,0,1,.25.25v14.5a.25.25,0,0,1-.25.25H5.75a.25.25,0,0,1-.25-.25ZM14.75,3A1.75,1.75,0,0,0,13,4.75v14.5A1.75,1.75,0,0,0,14.75,21h3.5A1.75,1.75,0,0,0,20,19.25V4.75A1.75,1.75,0,0,0,18.25,3ZM14.5,4.75a.25.25,0,0,1,.25-.25h3.5a.25.25,0,0,1,.25.25v14.5a.25.25,0,0,1-.25.25h-3.5a.25.25,0,0,1-.25-.25Z',
    stop: 'M5.75,3h12.5A2.75,2.75,0,0,1,21,5.75v12.5A2.75,2.75,0,0,1,18.25,21H5.75A2.75,2.75,0,0,1,3,18.25V5.75A2.75,2.75,0,0,1,5.75,3Zm0,1.5A1.25,1.25,0,0,0,4.5,5.75v12.5A1.25,1.25,0,0,0,5.75,19.5h12.5a1.25,1.25,0,0,0,1.25-1.25V5.75A1.25,1.25,0,0,0,18.25,4.5Z',
};

const viewBox = `0 0 ${2 * r + stroke} ${2 * r + stroke}`;
const strokeWidth = `${stroke}px`;

// prettier-ignore
const d = `M ${r + stroke / 2}, ${r + stroke / 2} m -${r}, 0 a ${r},${r} 0 1,0 ${2 * r},0 a ${r},${r} 0 1,0 ${-2 * r},0`;

const ButtonAutoplay: Component<Partial<Options>> = ($props) => {
    const props = mergeProps(defaultProps, $props);

    const { i18n } = useSlidy();

    const setTitle = (state: State) => {
        if (state === 'play') {
            return i18n.stop;
        } else if (state === 'stop') {
            return i18n.play;
        }
    };

    return (
        <div class="slidy-autoplay" style={{ '--slidy-autoplay-stroke-length': 2 * Math.PI * r }}>
            <svg viewBox={viewBox}>
                <path
                    stroke="var(--slidy-counter-bg, #4e4e4ebf)"
                    stroke-width={strokeWidth}
                    fill="none"
                    d={d}
                />
                <path
                    class={`slidy-autoplay-indicator ${props.state}`}
                    stroke="var(--slidy-autoplay-indicator-accent, lightpink)"
                    stroke-width={strokeWidth}
                    fill="none"
                    d={d}
                />
            </svg>
            <button disabled={props.disabled} onClick={props.onClick} title={setTitle(props.state)}>
                <svg viewBox="0 0 24 24">
                    <path d={iconPath[props.state]} />
                </svg>
            </button>
        </div>
    );
};

export default ButtonAutoplay;
