// packages/svelte/src/components/Thumbnail/Thumbnail.svelte
<script lang="ts" module>
	import Core from "../Core/Core.svelte";
	import Image from "../Image/Image.svelte";

	import {  getContext } from "svelte";
	import { format } from "@slidy/assets/scripts/utils";
	import type { SlidyThumbOptions } from "./thumbnail.types";
	import type { I18NDict, SlidyStyles } from "@slidy/assets/types";
	import "@slidy/assets/styles/thumbnail.module.css";
</script>

<script lang="ts">
	let {
		active = 0,
		animation = undefined,
		background = false,
		clamp = 0,
		duration= 250,
		easing= (t) => t,
		getImgSrc = (item) => item.src ?? "",
		gravity = 0.75,
		indent = 0,
		index = 0,
		loop = false,
		sensity = 5,
		slides = [],
		snap = undefined, // `"start", "center", "end", "deck = undefined,
		select = () => {},
	}: Partial<SlidyThumbOptions> & { select: (index: number) => void } = $props()

	const classNames = getContext<SlidyStyles>("classNames");
	const i18n = getContext<I18NDict>("i18n");
</script>

<Core
	{animation}
	{clamp}
	{duration}
	{easing}
	{gravity}
	{indent}
	{index}
	{loop}
	{sensity}
	{snap}
	tag="nav"
	axis="x"
	className={classNames?.thumbnails}
>
	{#each slides as item, i (item.id ?? getImgSrc(item) ?? i)}
		{@const title = format(i18n.slideN, i + 1)}
		<button
			aria-current={i === active ? "true" : undefined}
			aria-label={title}
			aria-roledescription="slide"
			class={classNames.thumbnail}
			class:active={i === active}
			class:bg={background}
			style:--_slidy-slide-bg={background ? `url(${getImgSrc(item)})` : ""}
			{title}
			onclick={() => select(i)}
		>
			{#if !background}
				<Image src={getImgSrc(item)} {...item} />
			{/if}
		</button>
	{/each}
</Core>

// packages/solid/src/components/Thumbnail/Thumbnail.tsx
import { mergeProps, For, Show } from 'solid-js';
import { Core, Image } from '..';
import { useSlidy } from '../Slidy/Slidy';
import { format } from '@slidy/assets/scripts/utils';

import type { Props } from './thumbnail.types';
import type { VoidComponent } from 'solid-js';

import '@slidy/assets/styles/thumbnail.module.css';

const defaultProps: Props = {
    active: 0,
    animation: undefined,
    axis: 'x',
    background: false,
    clamp: 0,
    duration: 250,
    easing: (t) => t,
    getImgSrc: (item) => (item as unknown as { src: string }).src ?? '',
    gravity: 0.75,
    indent: 0,
    index: 0,
    loop: false,
    sensity: 5,
    slides: [],
    snap: undefined,
};

const Thumbnail: VoidComponent<Partial<Props>> = ($props) => {
    const props = mergeProps(defaultProps, $props);

    const { classNames, i18n } = useSlidy();

    return (
        <Core {...props} tag="nav" className={classNames?.thumbnails}>
            <For each={props.slides}>
                {(item, i) => {
                    const active = () => props.active === i();
                    const title = () => format(i18n.slideN, i() + 1);

                    return (
                        <button
                            type="button"
                            aria-current={active() ? 'true' : undefined}
                            aria-label={title()}
                            title={title()}
                            aria-roledescription="slide"
                            class={classNames.thumbnail}
                            classList={{
                                active: active(),
                                bg: props.background,
                            }}
                            style={{
                                '--_slidy-slide-bg': props.background
                                    ? `url(${props.getImgSrc?.(item)})`
                                    : '',
                            }}
                            onClick={() => props.onSelect?.(i())}
                        >
                            <Show when={!props.background}>
                                <Image {...item} src={props.getImgSrc?.(item)} />
                            </Show>
                        </button>
                    );
                }}
            </For>
        </Core>
    );
};

export default Thumbnail;
