// packages/svelte/src/components/Navigation/Navigation.svelte
<script lang="ts">
	import { getContext } from "svelte";
	import { format } from "@slidy/assets/scripts/utils";
	import { generateIndexes } from "@slidy/assets/scripts/navigation";
	import { iconChevron } from "@slidy/assets/icons";
	import type { I18NDict, SlidyStyles } from "@slidy/assets/types";
	import "@slidy/assets/styles/navigation.module.css";

	export let current: number;
	export let start: number;
	export let end: number;
	export let ordinal = false;
	export let vertical = false;
	export let limit = 7;
	export let siblings = 1;

	const classNames = getContext<SlidyStyles>("classNames");
	const i18n = getContext<I18NDict>("i18n");

	const setTitle = (i: number) => {
		if (i === start) {
			return i18n.first;
		} else if (i === end) {
			return i18n.last;
		} else {
			return format(i18n.slideN, i);
		}
	};

	// Too many items -> should be ordinal for accessibility and responsiveness
	$: ordinal = end - start + 1 > limit && true;
	$: indices = generateIndexes({ current, start, end, limit, siblings });
</script>

<!-- svelte-ignore a11y-role-supports-aria-props -->
<nav
	aria-label="pagination"
	aria-orientation="{vertical ? "vertical" : "horizontal"}"
	class="{classNames?.nav}"
>
	<button
		aria-label="{i18n.first}"
		class="{classNames["nav-item"]} arrow"
		data-step={-1}
		disabled={current <= 1}
		title="{i18n.prev}"
	>
		<svg viewBox="{iconChevron.viewBox}">
			<path d="{iconChevron.path}" />
		</svg>
	</button>
	{#each indices as item}
		{@const active = item === current}
		{@const contents = item < 0 ? "…" : item}
		{@const ellipsis = item < 0}
		{@const title = setTitle(item)}
		<slot name="nav-item" index={item} {active}>
			<button
				aria-current={active ? "true" : undefined}
				aria-label={title}
				class={classNames["nav-item"]}
				class:active
				class:ellipsis
				class:ordinal
				data-index={ellipsis ? undefined : item - 1}
				disabled={ellipsis}
				{title}
			>
				{ordinal ? contents : ""}
			</button>
		</slot>
	{/each}
	<button
		aria-label="{i18n.first}"
		class="{classNames["nav-item"]} arrow"
		data-step={1}
		disabled={current >= end}
		title="{i18n.next}"
	>
		<svg viewBox="{iconChevron.viewBox}">
			<path d="{iconChevron.path}" />
		</svg>
	</button>
</nav>

// packages/solid/src/components/Navigation/Navigation.tsx
import { mergeProps, For } from 'solid-js';
import { useSlidy } from '../Slidy/Slidy';

import { generateIndexes } from '@slidy/assets/scripts/navigation';
import { format } from '@slidy/assets/scripts/utils';
import { iconChevron } from "@slidy/assets/icons";

import '@slidy/assets/styles/navigation.module.css';

import type { VoidComponent } from 'solid-js';
import type { Props } from './Navigation.types'

const defaultProps = {
    ordinal: false,
    vertical: false,
    limit: 7,
    siblings: 1,
};

const Navigation: VoidComponent<Props> = ($props) => {
    const props = mergeProps(defaultProps, $props);

    const { i18n, classNames } = useSlidy();

    const getTitle = (i: number) => {
        if (i === props.start) {
            return i18n.first;
        } else if (i === props.end) {
            return i18n.last;
        } else {
            return format(i18n.slideN, i);
        }
    };

    const ordinal = () => {
        return props.end - props.start + 1 > props.limit && true;
    };

    const indices = () => {
        return generateIndexes({
            current: props.current,
            start: props.start,
            end: props.end,
            limit: props.limit,
            siblings: props.siblings,
        });
    };

    return (
        <nav
            class={classNames?.nav}
            aria-orientation={props.vertical ? 'vertical' : 'horizontal'}
            aria-label="pagination"
        >
            	<button
		            aria-label={i18n.first}
		            class={classNames["nav-item"] + ' arrow'}
		            data-step={-1}
		            disabled={props.current <= 1}
		            title={i18n.prev}
	            >
                <svg viewBox={iconChevron.viewBox}>
                    <path d={iconChevron.path} />
                </svg>
            </button>
            <For each={indices()}>
                {(item) => {
                    const active = () => props.current === item;
                    const contents = () => (item < 0 ? '…' : item);
                    const ellipsis = () => item < 0;
                    const title = getTitle(item);

                    return (
                        <button
                            aria-current={active() ? 'true' : undefined}
                            aria-label={title}
                            classList={{
                                [classNames['nav-item']]: true,
                                
                                active: active(),
                                ellipsis: ellipsis(),
                                ordinal: ordinal(),
                            }}
                            data-index={ellipsis() ? undefined : item - 1}
                            disabled={ellipsis()}
                            title={title}
                        >
                            {ordinal() ? contents() : ''}
                        </button>
                    );
                }}
            </For>
            <button
                aria-label={i18n.first}
                class={classNames["nav-item"] + ' arrow'} 
                data-step={1}
                disabled={props.current >= props.end}
                title={i18n.next}
	        >
		        <svg viewBox={iconChevron.viewBox}>
			        <path d={iconChevron.path} />
		        </svg>
	        </button>
        </nav>
    );
};

export default Navigation;
