// packages/react/src/components/Image/Image.tsx
import { useSlidy } from '../Context';
import type { FC } from 'react';

import '@slidy/assets/styles/image.module.css';

type ImgNativeAttrs = Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'loading' | 'class' | 'id'>;

interface Props extends ImgNativeAttrs {
    lazy?: boolean;
    id?: string | number;
}

const Image: FC<Props> = ({ lazy = false, decoding = 'auto', id, ...rest }) => {
    const { classNames } = useSlidy();

    return (
        <img
            {...rest}
            className={classNames['img']}
            id={id ? String(id) : undefined}
            alt={rest.alt}
            loading={lazy ? 'lazy' : undefined}
        />
    );
};

export default Image;

// packages/svelte/src/component/components/Image.svelte
<img
	{alt}
	class="slidy-image {className}"
	loading={lazy ? "lazy" : undefined}
	{src}
	{width}
	{height}
	{style}
	{...$$restProps}
/>

<script lang="ts">
	export let src = "";
	export let width: number | string | undefined = undefined;
	export let height: number | string | undefined = undefined;
	export let alt = "";
	export let lazy = false;
	export let style = "";
	export let className = "";

	import "./image.module.css";
</script>
