// packages/react/src/components/Arrow/Arrow.tsx
import { useSlidy } from '../Context';
import { clsx } from 'clsx';

import '@slidy/assets/styles/arrow.module.css';

import type { FC, PropsWithChildren } from 'react';

interface Props {
    direction: number;
    step: number;
    loop?: boolean;
    index: number;
    items?: number;
    vertical: boolean;
}

const Arrow: FC<PropsWithChildren<Props>> = ({ direction = 1, step = 1, index = 0, items = 0, vertical = false, loop = false, children }) => {
    const { classNames, i18n } = useSlidy();

    const disabled = direction < 0
        ? index === 0 && !loop
        : index === items - 1 && !loop;

    const title = direction > 0 ? i18n.prev : i18n.next;

    return (
        <button
            aria-label={title}
            aria-orientation={vertical ? 'vertical' : 'horizontal'}
            className={clsx(classNames.arrow, direction < 1 && 'prev')}
            data-step={direction * step}
            disabled={disabled}
            title={title}
        >
            {children}
        </button>
    );
};

export default Arrow;

// packages/svelte/src/components/Arrow/Arrow.svelte
<script lang="ts" module>
	import { getContext } from "svelte";
	import "@slidy/assets/styles/arrow.module.css";
	import type { I18NDict, SlidyStyles } from "@slidy/assets/types";
</script>

<script lang="ts">
	let {
		direction = 1,
		loop = false,
		index= 0,
		items = 0,
		step = 1,
		vertical = false,
		children
	} = $props()

	const classNames = getContext<SlidyStyles>("classNames");
	const i18n = getContext<I18NDict>("i18n");

	const disabled = $derived(direction < 0
		? index === 0 && !loop
		: index === items - 1 && !loop);


	const title = $derived(direction > 0 ? i18n.next : i18n.prev);
</script>

<!-- svelte-ignore a11y_role_supports_aria_props_implicit -->
<button
	aria-label={title}
	aria-orientation={vertical ? "vertical" : "horizontal"}
	class={classNames.arrow}
	class:prev={direction < 1}
	data-step={direction * step}
	{disabled}
	{title}
>
	{@render children?.()}
</button>
