// packages/svelte/dev/src/components/Sidemenu.svelte
<aside class="side-menu" class:open>
    <div
        class="backdrop"
        title="Close sidebar"
        aria-label="Close sidebar"
        on:click={close}
        tabindex="0"
    />
    <section class="contents">
        <slot />
    </section>
</aside>

<svelte:window on:keydown={handleKeydown} />

<script lang="ts">
    import './side-menu.module.css';

    export let open = false;

    const close = () => (open = !open);
    const handleKeydown = (event: KeyboardEvent) =>
        event.code === 'Escape' && close();
</script>

// packages/solid/src/dev/components/Sidemenu.tsx
import type { FlowComponent } from 'solid-js';
import type { Channel } from '../lib/channel';
import { onMount, onCleanup } from 'solid-js';

import './side-menu.module.css';

interface Props {
    controlPanel: Channel<boolean>;
}

const Sidemenu: FlowComponent<Props> = (props) => {
    const controlPanel = props.controlPanel;

    const close = () => controlPanel((v) => !v);

    const handleKeydown = (event: KeyboardEvent) => {
        return event.code === 'Escape' && close();
    };

    onMount(() => addEventListener('keydown', handleKeydown));
    onCleanup(() => removeEventListener('keydown', handleKeydown));

    return (
        <aside class="side-menu" classList={{ open: controlPanel() }}>
            <div
                class="backdrop"
                title="Close sidebar"
                aria-label="Close sidebar"
                onClick={close}
                tabindex="0"
            />
            <section class="contents">{props.children}</section>
        </aside>
    );
};

export default Sidemenu;
