// packages/react/src/components/Progress/Progress.tsx
import { useSlidy } from '../Context';
import { s } from '../../utils';
import { execute, noop } from '@slidy/assets/scripts/utils';

import '@slidy/assets/styles/progress.module.css';

import type { FC } from 'react';

interface Props {
    value: number;
    max: number;
    vertical: boolean;
    onInput: (e: InputEvent) => void;
}

const defaultProps: Props = {
    value: 0,
    max: 1,
    vertical: false,
    onInput: noop
};

const Progress: FC<Props> = (props) => {
    const { classNames } = useSlidy();

    const progress = () => Math.ceil((props.value * 100) / props.max);
    const size = () => Math.ceil(100 / props.max);

    return (
        <div
            className={classNames.progress}
            aria-orientation={props.vertical ? 'vertical' : 'horizontal'}
            style={s({
                '--_slidy-progress-size': size() + '%',
                '--_slidy-progress': progress() + '%',
            })}
        >
            <input
                className="slidy-progress-input"
                type="range"
                value={props.value}
                min={1}
                max={props.max}
                name="slidy-progress"
                onInput={execute(props.onInput)}
            />
            <span className={classNames['progress-handle']} />
        </div>
    );
};

Progress.defaultProps = defaultProps;

export default Progress;

// packages/solid/src/components/Progress/Progress.tsx
import { useSlidy } from '../Slidy/Slidy';
import { mergeProps } from 'solid-js';
import { noop } from '@slidy/assets/scripts/utils';
import { s } from '../../utils';

import '@slidy/assets/styles/progress.module.css';

import type { VoidComponent } from 'solid-js';
import type { Props } from './Progress.types'

const defaultProps: Props = {
    value: 0,
    max: 1,
    vertical: false,
    onInput: noop,
};

const Progress: VoidComponent<Partial<Props>> = ($props) => {
    const props = mergeProps(defaultProps, $props);

    const { classNames } = useSlidy();

    const progress = () => Math.ceil((props.value * 100) / props.max);
    const size = () => Math.ceil(100 / props.max);

    return (
        <div
            class={classNames.progress}
            aria-orientation={props.vertical ? 'vertical' : 'horizontal'}
            style={s({
                '--_slidy-progress-size': size() + '%',
                '--_slidy-progress': progress() + '%',
            })}
        >
            <input
                class="slidy-progress-input"
                type="range"
                value={props.value}
                min={1}
                max={props.max}
                name="slidy-progress"
                onInput={props.onInput}
            />
            <span class={classNames['progress-handle']} />
        </div>
    );
};

export default Progress;
