// packages/svelte/src/components/Image/Image.svelte
<script lang="ts" module>
	import { getContext } from "svelte";
	import type { SlidyStyles } from "@slidy/assets/types";
	import "@slidy/assets/styles/image.module.css";
</script>

<script lang="ts">
	let {
		alt = "",
		decoding = "auto",
		height = undefined,
		lazy = false,
		src = "",
		width = undefined,
	}: Partial<{
		alt: string,
		decoding: "sync" | "async" | "auto" ,
		height: number | string | undefined,
		lazy: boolean,
		src: string,
		width: number | string | undefined
	}> = $props()

	const classNames = getContext<SlidyStyles>("classNames");
</script>

<img
	{alt}
	{src}
	{width}
	{height}
	{decoding}
	class={classNames["img"]}
	loading={lazy ? "lazy" : undefined}
/>

// packages/solid/src/components/Image/Image.tsx
import { useSlidy } from '../Slidy/Slidy';
import { splitProps, mergeProps } from 'solid-js';

import '@slidy/assets/styles/image.module.css';

import type { Component } from 'solid-js';
import type { Props } from './Image.types'

const defaultProps: Props = {
    decoding: 'auto',
    lazy: false,
};

const Image: Component<Partial<Props>> = ($props) => {
    const props = mergeProps(defaultProps, $props);
    const [it, rest] = splitProps(props, ['lazy', 'id']);

    const { classNames } = useSlidy();

    return (
        <img
            {...rest}
            class={classNames['img']}
            id={it.id as string}
            loading={it.lazy ? 'lazy' : undefined}
        />
    );
};

export default Image;
