// packages/solid/src/components/Navigation/Navigation.tsx
import { mergeProps, For } from 'solid-js';
import { useSlidy } from '../Slidy/Slidy';

import { generateIndexes, format } from '@slidy/assets/scripts';

import '@slidy/assets/styles/navigation.module.css';

import type { VoidComponent } from 'solid-js';

interface Options {
    current: number;
    start: number;
    end: number;
    ordinal: boolean;
    vertical: boolean;
    limit: number;
    siblings: number;
}

const defaultProps = {
    ordinal: false,
    vertical: false,
    limit: 7,
    siblings: 1,
};

type Props = Pick<Options, 'start' | 'current' | 'end'> &
    Partial<Omit<Options, 'start' | 'current' | 'end'>>;

const Navigation: VoidComponent<Props> = ($props) => {
    const props = mergeProps(defaultProps, $props);

    const { i18n, classNames } = useSlidy();

    const getTitle = (i: number) => {
        if (i === props.start) {
            return i18n.first;
        } else if (i === props.end) {
            return i18n.last;
        } else {
            return format(i18n.slideN, i);
        }
    };

    const ordinal = () => {
        return props.end - props.start + 1 > props.limit && true;
    };

    const indices = () => {
        return generateIndexes({
            current: props.current,
            start: props.start,
            end: props.end,
            limit: props.limit,
            siblings: props.siblings,
        });
    };

    return (
        <nav
            class={classNames?.nav}
            classList={{ vertical: props.vertical }}
            aria-label="pagination"
        >
            <For each={indices()}>
                {(item) => {
                    const active = () => props.current === item;
                    const contents = () => (item < 0 ? '…' : item);
                    const ellipsis = () => item < 0;
                    const title = () => getTitle(item);

                    return (
                        <button
                            aria-current={active() ? 'true' : undefined}
                            aria-label={title()}
                            class={classNames['nav-item']}
                            classList={{
                                active: active(),
                                ellipsis: ellipsis(),
                                ordinal: ordinal(),
                            }}
                            data-index={ellipsis() ? undefined : item - 1}
                            disabled={ellipsis()}
                            title={title()}
                        >
                            {ordinal() ? contents() : ''}
                        </button>
                    );
                }}
            </For>
        </nav>
    );
};

export default Navigation;

// packages/react/src/components/Navigation/Navigation.tsx
import { generateIndexes } from '@slidy/assets/scripts/navigation';
import { useSlidy } from '../Context';
import { format } from '@slidy/assets/scripts/utils';
import { clsx } from 'clsx';

import '@slidy/assets/styles/navigation.module.css';

import type { FC } from 'react';

interface Options {
    current: number;
    start: number;
    end: number;
    ordinal: boolean;
    vertical: boolean;
    limit: number;
    siblings: number;
}

const defaultProps = {
    ordinal: false,
    vertical: false,
    limit: 7,
    siblings: 1,
};

type Props = Pick<Options, 'start' | 'current' | 'end'> &
    Partial<Omit<Options, 'start' | 'current' | 'end'>>;

const Navigation: FC<Props> = ($props) => {
    const props = $props as Options;

    const { i18n, classNames } = useSlidy();

    const getTitle = (i: number) => {
        if (i === props.start) {
            return i18n.first;
        } else if (i === props.end) {
            return i18n.last;
        } else {
            return format(i18n.slideN, i);
        }
    };

    const ordinal = props.end - props.start + 1 > props.limit && true;

    const indices = generateIndexes({
        current: props.current,
        start: props.start,
        end: props.end,
        limit: props.limit,
        siblings: props.siblings,
    });

    return (
        <nav
            className={clsx(classNames?.nav, props.vertical && 'vertical')}
            aria-label="pagination"
        >
            {indices.map((item, i) => {
                const active = props.current === item;
                const contents = item < 0 ? '…' : item;
                const ellipsis = item < 0;
                const title = getTitle(item);

                return (
                    <button
                        className={clsx(
                            classNames['nav-item'],
                            active && 'active',
                            ellipsis && 'ellipsis',
                            ordinal && 'ordinal'
                        )}
                        data-index={ellipsis ? undefined : item - 1}
                        disabled={ellipsis}
                        aria-current={active ? 'true' : undefined}
                        aria-label={title}
                        title={title}
                        key={i}
                    >
                        {ordinal ? contents : ''}
                    </button>
                );
            })}
        </nav>
    );
};

Navigation.defaultProps = defaultProps;

export default Navigation;
