// packages/solid/src/components/Image/Image.tsx
import { useSlidy } from '../Slidy/Slidy';
import { splitProps, mergeProps } from 'solid-js';

import '@slidy/assets/styles/image.module.css';

import type { JSX, Component } from 'solid-js';

type ImgNativeAttrs = Omit<JSX.ImgHTMLAttributes<HTMLImageElement>, 'loading' | 'class' | 'id'>;

interface Props extends ImgNativeAttrs {
    lazy?: boolean;
    id?: string | number;
}

const defaultProps: Props = {
    decoding: 'auto',
    lazy: false,
};

const Image: Component<ImgNativeAttrs> = ($props) => {
    const props = mergeProps(defaultProps, $props);
    const [it, rest] = splitProps(props, ['lazy', 'id']);

    const { classNames } = useSlidy();

    return (
        <img
            {...rest}
            class={classNames['img']}
            id={it.id ? String(it.id) : undefined}
            loading={it.lazy ? 'lazy' : undefined}
        />
    );
};

export default Image;

// packages/react/src/components/Image/Image.tsx
import React from 'react';
import { useSlidy } from '../Context';

import '@slidy/assets/styles/image.module.css';

import type { FC } from 'react';

type ImgNativeAttrs = Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'loading' | 'class' | 'id'>;

interface Props extends ImgNativeAttrs {
    lazy?: boolean;
    id?: string | number;
}

const defaultProps: Props = {
    decoding: 'auto',
    lazy: false,
};

const Image: FC<Props> = (props) => {
    const { lazy, id, ...rest } = props;

    const { classNames } = useSlidy();

    return (
        <img
            {...rest}
            className={classNames['img']}
            id={id ? String(id) : undefined}
            loading={lazy ? 'lazy' : undefined}
        />
    );
};

Image.defaultProps = defaultProps;

export default Image;
